# Generated by Django 3.0 on 2021-11-09 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerFile',
            new_name='Exer',
        ),
    ]
