# Generated by Django 3.0 on 2021-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exers', '0002_auto_20211109_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='exer',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
