# Generated by Django 3.0 on 2021-12-14 20:15

from django.db import migrations, models
import exers.models


class Migration(migrations.Migration):

    dependencies = [
        ('exers', '0003_exer_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exer',
            name='sou_file',
            field=models.FileField(null=True, upload_to=exers.models.namer),
        ),
        migrations.AlterField(
            model_name='exer',
            name='ex_file',
            field=models.FileField(null=True, upload_to=exers.models.namer),
        ),
    ]
